export interface SuggestedItem {
  Bin: string;
  Category: string;
  Id: number;
  PreTransit: number;
  InTransit: number;
  ItemDesc: string;
  ItemNmbr: string;
  Location: string;
  Vendor: number;
  MaxOrderQty: number;
  MinOrderQty: number;
  OrderPointQty: number;
  OrderUpToLvl: number;
  PackSize: number | string;
  PalletQty: number;
  PalletHeight: number;
  QtyAllocated: number;
  QtyAllocatedByDate: number;
  QtyAvailable: number;
  QtyBackordered: number;
  QtyOnHand: number;
  OnHandHEA: number;
  OnHandNSW: number;
  OnHandQLD: number;
  OnHandSA: number;
  OnHandVIC: number;
  OnHandWA: number;
  AllocHEA: number;
  AllocNSW: number;
  AllocQLD: number;
  AllocSA: number;
  AllocVIC: number;
  AllocWA: number;
  AvailHEA: number;
  AvailNSW: number;
  AvailQLD: number;
  AvailSA: number;
  AvailVIC: number;
  AvailWA: number;
  Notes: string;
  ToTransfer: number;
  QtyRequired: number | null;
  Suggested: number | null;
  UnderStocked?: boolean;
  ToFill?: number;
  Spaces: number;
}